### ISSUE TITLE
Trouble with the installation.

### ISSUE THREAD

**Issue by MCLawton** [ermst4r/df#1]
Hello,

I'm trying to install your program DF Builder. But I have trouble with the installation. Because this part is a little unclear to me what to do now, and how to do it. Because i can't find the npm to install. Can you please explain to me what to do here? 

1. cd to/dfdirectory
2. Run npm install
3. Run npm run dev/production (depending on your environment)
5. run php artisan key:generate
5. install nvm and use node v.6.2.9 (curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash)
6. php artisan migrate --seed 
7. php artisan module:migrate Category

Kind regards,

**Comment by ermst4r** [comment]
Hello Conan,

Do you have node JS installed on your machine?

**Comment by MCLawton** [comment]
Yes I have.

**Comment by ermst4r** [comment]
can you post an output of the console?
thanks

**Comment by MCLawton** [comment]
Sorry, but I don´t really know how to work with node.js. So I don´t know what to do.

**Comment by yasinkocak** [comment]
Here u can download and install NodeJS
https://nodejs.org/en/

Here u can read what is Nodejs
https://scotch.io/@rakeshpatel/what-nodejs-is-all-about

This article tells u npm build tool
https://scotch.io/tutorials/using-npm-as-a-build-tool

**Comment by MCLawton** [comment]
Bedankt voor de links die je me stuurde, daardoor snapte ik het wel beter.

Maar nu heb ik een andere probleem, heb ik iets gemist of moet ik iets veranderen? Ik zie dat hij naar de map "vendor" wilt gaan die er niet is. Maar niks werkt als ik dat verander.

C:\Datafeed\df-master\df-master>php artisan key:generate
PHP Warning:  require(C:\Datafeed\df-master\df-master\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\Datafeed\df-master\df-master\bootstrap\autoload.php on line 17

Warning: require(C:\Datafeed\df-master\df-master\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\Datafeed\df-master\df-master\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\Datafeed\df-master\df-master\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\Datafeed\df-master\df-master\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\Datafeed\df-master\df-master\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\Datafeed\df-master\df-master\bootstrap\autoload.php on line 17

**Comment by ermst4r** [comment]
hi @MCLawton , did you tried to run composer install?
cd to the laravel directory and make sure you have composer installed...

Try this:
`php composer.phar install`

Or try this
`composer install`

If you are running vagrant  i suggest you run these commands.


`sudo add-apt-repository ppa:webupd8team/java 

sudo apt-get update $ sudo apt-get install oracle-java8-installer

sudo add-apt-repository --yes ppa:ondrej/php 

sudo apt-get update sudo apt-get install --yes 
php7.0-common 
php7.0-cli 
php7.0-json 
php7.0-xml 
php7.0-dev 
php7.0-fpm 
php7.0-mcrypt 
php7.0-xmlrpc 
php7.0-mysql 
php7.0-gd 
php7.0-curl 
php7.0-mbstring 
php7.0-soap 
php-pear`

**Comment by MCLawton** [comment]
I have installed Composer. But it still doesen't work.

C:\Datafeed\df-master\df-master>composer
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.5.5 2017-12-01 14:42:57

**Comment by yasinkocak** [comment]
Learn more about package manager Composer
https://scotch.io/tutorials/a-beginners-guide-to-composer

**Comment by MCLawton** [comment]
I have accomplished to generate my php artisan key.

But now when I try to install nvm this happens:

C:\Datafeed\df-master\df-master>curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
'bash' is not recognized as an internal or external command,
operable program or batch file.

I already downloaded cURL, and I had to move the curl.exe file in my C:\Datafeed\df-master\df-master> before it could see curl.

I can't find on the internet what to do here.

**Comment by yasinkocak** [comment]
Your PHP need extension cURL
http://php.net/manual/en/curl.installation.php

If u have any question about how to install php extension curl
https://stackoverflow.com/questions/tagged/php

**Comment by MCLawton** [comment]
Thank you i have managed to use the command cURL.
But now when I try to execute the following command:

C:\Datafeed\df-master\df-master>php artisan module:migrate Category


  [Nwidart\Modules\Exceptions\ModuleNotFoundException]
  Module [Category] does not exist!

What do I have to do now?

**Comment by MCLawton** [comment]
I think that I did all the steps right, but now I am at the last step and I don't know where I have to put the command:

Finally you need to start the cronjob.

* * * * * php /path-to-your-project/artisan schedule:run >> /dev/null 2>&1

Can you tell me where I have to put that?
